get:
  description: 商品列表
  queryParameters:
    isStar:
      description: 是否精选
      type: boolean
      required: false
      example: true
  responses:
    200:
      body:
        type: Product[]
        example: !include ./products_200.json

/{productId}:
  get:
    securedBy: [oauth_token]
    description: 商品详情
    (controller): product#getProductDetail
    (uriParameters):
      productId:
        description: productId
        example: aaaa
    responses:
      200:
        body:
          type: Product
          example: !include ./product_200.json
