/:
  get:
    description: 文章列表
    responses:
      200:
        body:
          type: ArticleListVO[]
          example: !include ./articles_list_200.json
/{id}:
  get:
    description: 文章详情
    (uriParameters):
      id:
        description: article id
        example: bbbb
    responses:
      200:
        body:
          type: Article
          example: !include ./article_200.json

