ArticleListVO:
  type: object
  properties:
    articleId:
      type: string
      required: false
    title:
      type: string
      required: false
    author: string
Article:
  type: object
  properties:
    articleId:
      type: string
      required: false
    title:
      type: string
      required: false
    author: string
    paragraphs: Paragraph[]
Paragraph:
  type: object
  properties:
    title:
    text:
    product:
      type: Product
      required: false
Product:
  type: object
  properties:
    productId:
      type: string
      minLength: 4
      maxLength: 36
    productName: string
    description: string
    price: number
