post:
  description: 登录
  body:
    application/json:
      properties:
        username:
          description: 用户名
          type: string
          required: true
        password:
          description: 密码
          type: string
          required: true
    example: {password: 123, name: name}
  (runner):
    # 注意：这里的相对路径是相对于工程目录，而不是当前文件。
    after: ./runner/afterLogin.js
  responses:
    200:
      body:
        type: string
        example: fdafda232432fdaxfda25dfa
